### ISSUE TITLE
Custom Derma

### ISSUE THREAD

**Issue by landnevermore** [Guthen/guthscpbase#2]
maybe you could start using PixelUI or XeninUI so the Addons look more "Modern"
(could be a config option like you mentioned)

**Comment by Guthen** [comment]
It will more likely not be done, I don't want to force servers to install a graphical lib nor to develop multiple versions of the menu for each lib (and to maintain it). 

A nice solution would be to make a module of guthscpbase for that (with the upcoming update), just need to think about how to allow this, maybe running a hook each time I attempt to create a vgui or maybe using a lookup table for each vgui so you can override them..

**Comment by Guthen** [comment]
Won't be worked on, would be unnecessary work in my opinion
