### ISSUE TITLE
Remaster Branch: Add Reset configuration button for each modules

### ISSUE THREAD

**Issue by Certurix** [Guthen/guthscpbase#5]
### Description

This button when pressed, will show a modal to confirm if the superadmin player want to erase every configuration fields inside the module. When pressing the "OK" state button, the data configuration file from the module will be erased and every fields will be remplaced by their default values, available inside the main.lua of the module.

**Comment by Guthen** [comment]
Resolved in https://github.com/Guthen/guthscpbase/commit/c74eceaba5e4e21d6a8cbd16bf9a81e8d6c404d1
