### ISSUE TITLE
New Config Type : Color

### ISSUE THREAD

**Issue by Certurix** [Guthen/guthscpbase#8]
## Description
Add a new config type for every module : the Color type.
When used, it will display a color palette for users to choose the color from.
Then, this type will return the color from the variable for each number types.
Here an example of how it would looks like in the config file:
```lua
			{
				type = "Color",
				name = "My awesome color",
				id = "beautifulcolor",
				desc = "Configure your own color! For HUDs, menus and more!",
				default = Color(255,255,255,0),
			},
```
Then, to get colors from this type, we would need to do that : guthscp.configs.{modulename}.beautifulcolor.r , g, b and a)

I'm not the best to explain things, so don't hesitate to ask me if you didn't understood something.

**Comment by Guthen** [comment]
This is done, here is a preview below.

### Code
```lua
{
    type = "Color",
    name = "Test Color",
    id = "test_color",
    desc = "This is a test color variable",
    default = Color( 200, 100, 0 ),
},
```

### Result
![gif](https://github.com/Guthen/guthscpbase/assets/33220603/040329e3-55eb-47c0-8ae4-df62bd05c0d9)

You can set the color either by using the hexadecimal textentry or by using the color combo after populating it with the button.
